const FETCH_PRICE_REQUEST = 'FETCH_PRICE_REQUEST'
const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS'
const FETCH_PRICE_FUILURE = 'FETCH_PRICE_FUILURE'
const SET_TEXT = 'SET_TEXT'
const SET_CONVERT_DATE = 'SET_CONVERT_DATE'

export {
  FETCH_PRICE_REQUEST,
  FETCH_PRICE_SUCCESS,
  FETCH_PRICE_FUILURE,
  SET_TEXT,
  SET_CONVERT_DATE,
}