const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST'
const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS'
const FETCH_RATES_FUILURE = 'FETCH_RATES_FUILURE'

const FETCH_PRICE_REQUEST = 'FETCH_PRICE_REQUEST'
const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS'
const FETCH_PRICE_FUILURE = 'FETCH_PRICE_FUILURE'
const SET_CONVERTER_TEXT = 'SET_CONVERTER_TEXT'
const SET_CONVERTER_DATE = 'SET_CONVERTER_DATE'

const FETCH_ARCHIVE_REQUEST = 'FETCH_ARCHIVE_REQUEST'
const FETCH_ARCHIVE_SUCCESS = 'FETCH_ARCHIVE_SUCCESS'
const FETCH_ARCHIVE_FUILURE = 'FETCH_ARCHIVE_FUILURE'
const SET_ARCHIVE_BASE = 'SET_ARCHIVE_BASE'
const SET_ARCHIVE_DATE = 'SET_ARCHIVE_DATE'

const FETCH_AVIALABLE_REQUEST = 'FETCH_AVIALABLE_REQUEST'
const FETCH_AVIALABLE_SUCCESS = 'FETCH_AVIALABLE_SUCCESS'
const FETCH_AVIALABLE_FUILURE = 'FETCH_AVIALABLE_FUILURE'

export {
  FETCH_RATES_REQUEST,
  FETCH_RATES_SUCCESS,
  FETCH_RATES_FUILURE,

  FETCH_PRICE_REQUEST,
  FETCH_PRICE_SUCCESS,
  FETCH_PRICE_FUILURE,
  SET_CONVERTER_TEXT,
  SET_CONVERTER_DATE,

  FETCH_ARCHIVE_REQUEST,
  FETCH_ARCHIVE_SUCCESS,
  FETCH_ARCHIVE_FUILURE,
  SET_ARCHIVE_BASE,
  SET_ARCHIVE_DATE,

  FETCH_AVIALABLE_REQUEST,
  FETCH_AVIALABLE_SUCCESS,
  FETCH_AVIALABLE_FUILURE,
}